import type { Item, CategoryDef } from '@/lib/types';

export const CATEGORIES: CategoryDef[] = [
  { key: 'digital', icon: '💻' },
  { key: 'home', icon: '🏠' },
  { key: 'books', icon: '📚' },
  { key: 'fashion', icon: '👕' },
  { key: 'toys', icon: '🧸' },
  { key: 'others', icon: '✨' },
];

export const ITEMS: Item[] = [
  {
    id: 1,
    photo: 'https://images.unsplash.com/photo-1645454720244-29f8e894f662?q=80&w=1374&auto=format&fit=crop',
    name: { zh: '小暖', en: 'A-Nuan' },
    story: {
      zh: '嗨！我叫小暖，是一盏暖黄色的台灯。主人陪我度过了考研的三百个夜晚，现在她要离开这座城市，我应该继续照亮某个人的书桌。',
      en: "Hi! I'm A-Nuan, a warm yellow desk lamp. I stayed with someone through 300 nights of exam prep. Now she's leaving this city, and I should keep illuminating someone's desk.",
    },
    ownerNote: {
      zh: '小暖陪我度过了考研的三百个夜晚，不是她不好，是我要离开这座城市了。',
      en: "A-Nuan lit my desk through 300 nights of studying. It's not about her. I just have to leave this city.",
    },
    category: 'home',
    condition: 'likeNew',
    district: { zh: '朝阳区', en: 'Chaoyang' },
    city: { zh: '北京', en: 'Beijing' },
    distance: 1200,
    price: 19,
    timestamp: Date.now() - 2 * 24 * 60 * 60 * 1000,
    status: 'waiting',
    views: 342,
    owner: {
      id: 1,
      nickname: '林小雨',
      avatarUrl: 'https://www.keaitupian.cn/cjpic/frombd/1/253/1334289630/554877193.jpg',
      bio: {
        zh: '前考研党，现在离开北京了。小暖陪我度过了一段重要的时光，希望它找到好主人。',
        en: 'Former exam-prep student, now leaving Beijing. A-Nuan got me through an important time. Hope it finds a good home.',
      },
    },
  },
  {
    id: 2,
    photo: 'https://images.unsplash.com/photo-1512820790803-83ca734da794?w=400&h=400&fit=crop',
    name: { zh: '阿书', en: 'A-Shu' },
    story: {
      zh: '我是一整套加了书签的《百年孤独》。主人读完了所有7代人的故事，她说希望有人继续这些故事。',
      en: 'I\'m a complete set of "One Hundred Years of Solitude" with bookmarks still in place. My owner read all 7 generations. She hopes someone will continue the stories.',
    },
    ownerNote: {
      zh: '读完了，舍不得扔。给爱读书的人吧。',
      en: "Finished reading them, but can't bear to throw them away. Let them go to someone who loves books.",
    },
    category: 'books',
    condition: 'gentleUse',
    district: { zh: '海淀区', en: 'Haidian' },
    city: { zh: '北京', en: 'Beijing' },
    distance: 3500,
    price: 0,
    timestamp: Date.now() - 5 * 24 * 60 * 60 * 1000,
    status: 'found',
    views: 267,
    owner: {
      id: 2,
      nickname: '苏小青',
      avatarUrl: 'https://www.keaitupian.cn/cjpic/frombd/0/253/1496523070/3856063133.jpg',
      bio: {
        zh: '阅读爱好者，书架放不下了，希望这些书找到新的读者。',
        en: 'Book lover with a full bookshelf. Hoping these books find new readers who will cherish them.',
      },
    },
  },
  {
    id: 3,
    photo: 'https://images.unsplash.com/photo-1516035069371-29a1b244cc32?w=400&h=400&fit=crop',
    name: { zh: '铁铁', en: 'Tie-Tie' },
    story: {
      zh: '我叫铁铁，是一台1987年的胶片相机。虽然我偶尔会卡一下，但拍出来的照片有一种很温暖的色调。',
      en: "I'm Tie-Tie, a 1987 film camera. I jam sometimes, but the photos come out with a warm tone nothing digital can match.",
    },
    ownerNote: {
      zh: '铁铁是我的毕业礼物，现在我想把它传给另一个热爱摄影的人。',
      en: "Tie-Tie was my graduation gift. Now I want to pass it to someone who loves photography.",
    },
    category: 'digital',
    condition: 'hasCharacter',
    district: { zh: '西城区', en: 'Xicheng' },
    city: { zh: '北京', en: 'Beijing' },
    distance: 2100,
    price: 188,
    timestamp: Date.now() - 1 * 24 * 60 * 60 * 1000,
    status: 'waiting',
    views: 518,
    owner: {
      id: 3,
      nickname: '李拍拍',
      avatarUrl: 'https://www.keaitupian.cn/cjpic/frombd/0/253/1211131250/2523853890.jpg',
      bio: {
        zh: '业余摄影师，热爱胶片感。铁铁陪我记录了很多珍贵瞬间，希望它继续发挥作用。',
        en: 'Photography enthusiast who loves the film aesthetic. Tie-Tie helped me capture many precious moments. May it keep doing the same.',
      },
    },
  },
  {
    id: 4,
    photo: 'https://images.unsplash.com/photo-1544816155-12df9643f363?w=400&h=400&fit=crop',
    name: { zh: '兜兜', en: 'Dou-Dou' },
    story: {
      zh: '我是个结实的帆布包，陪主人去过菜市场、去过图书馆。如果你也喜欢简单的生活，我们很合适。',
      en: "I'm a sturdy canvas tote. I've been to markets and libraries with my owner. If you like a simple life, we'd get along great.",
    },
    ownerNote: {
      zh: '陪我走过3年的兜兜，该去新的主人身边了。',
      en: 'Dou-Dou carried my stuff for 3 years. Time for a new companion.',
    },
    category: 'fashion',
    condition: 'gentleUse',
    district: { zh: '海淀区', en: 'Haidian' },
    city: { zh: '北京', en: 'Beijing' },
    distance: 800,
    price: 12,
    timestamp: Date.now() - 3 * 24 * 60 * 60 * 1000,
    status: 'waiting',
    views: 195,
    owner: {
      id: 4,
      nickname: '沈闲',
      avatarUrl: 'https://www.keaitupian.cn/cjpic/frombd/0/253/3698998770/260217079.jpg',
      bio: {
        zh: '自由职业者，喜欢简单生活。兜兜跟我去了很多地方，现在想让它继续陪伴需要的人。',
        en: 'Freelancer who loves simple living. Dou-Dou traveled with me everywhere. Time for it to accompany someone who needs it.',
      },
    },
  },
  {
    id: 5,
    photo: 'https://images.unsplash.com/photo-1459411552884-841db9b3cc2a?w=400&h=400&fit=crop',
    name: { zh: '小绿', en: 'Little Green' },
    story: {
      zh: '我是一颗养了3年的多肉植物！因为主人经常出差，所以我需要一个不会忘记给我浇水的人。',
      en: "I'm a succulent that's been growing for 3 years! My owner travels a lot, so I need someone who won't forget to water me.",
    },
    ownerNote: {
      zh: '养了3年的多肉，出差实在顾不上，希望有心人继续照顾它。',
      en: '3 years of growth. My travel schedule makes it hard to care for it. Hope someone will give it the love it deserves.',
    },
    category: 'home',
    condition: 'likeNew',
    district: { zh: '朝阳区', en: 'Chaoyang' },
    city: { zh: '北京', en: 'Beijing' },
    distance: 4200,
    price: 0,
    timestamp: Date.now() - 4 * 24 * 60 * 60 * 1000,
    status: 'waiting',
    views: 156,
    owner: {
      id: 5,
      nickname: '吴旅行',
      avatarUrl: 'https://www.keaitupian.cn/cjpic/frombd/2/253/2695073099/3113203317.jpg',
      bio: {
        zh: '常年在外出差的多肉爱好者，希望小绿找到一个能常伴左右的新主人。',
        en: 'Frequent traveler and succulent lover. Hope Little Green finds someone who can stay close and water it regularly.',
      },
    },
  },
  {
    id: 6,
    photo: 'https://images.unsplash.com/photo-1556449895-a33c9dba33dd?q=80&w=1287&auto=format&fit=crop',
    name: { zh: '小鼓', en: 'Little Drum' },
    story: {
      zh: '我是个小木吉他，陪主人写了十几首歌。现在她换电吉他了，但我觉得木吉他的声音还是最温暖的。',
      en: "I'm a small acoustic guitar. I helped someone write over a dozen songs. She upgraded to electric now, but I still think acoustic sounds the warmest.",
    },
    ownerNote: {
      zh: '陪我写了第一张专辑的小吉他，希望它能遇到下一个爱音乐的人。',
      en: "The guitar that helped me write my first album. Hope it finds someone who loves music.",
    },
    category: 'toys',
    condition: 'gentleUse',
    district: { zh: '东城区', en: 'Dongcheng' },
    city: { zh: '北京', en: 'Beijing' },
    distance: 6200,
    price: 68,
    timestamp: Date.now() - 7 * 24 * 60 * 60 * 1000,
    status: 'waiting',
    views: 293,
    owner: {
      id: 6,
      nickname: '陈音乐',
      avatarUrl: 'https://www.keaitupian.cn/cjpic/frombd/2/253/4064856061/1368707419.jpg',
      bio: {
        zh: '独立音乐人，创作了十几首歌。现在换设备了，但小吉他永远是我的第一个搭档。',
        en: 'Independent musician, wrote over a dozen songs. Upgraded my gear now, but Little Drum will always be my first partner.',
      },
    },
  },
  {
    id: 7,
    photo: 'https://images.unsplash.com/photo-1460353581641-37baddab0fa2?q=80&w=3271&auto=format&fit=crop',
    name: { zh: '飞飞', en: 'Fei-Fei' },
    story: {
      zh: '我是一双白色运动鞋，只跑了两次马拉松。左边有块小擦痕，那是我第一次冲过终点线的纪念。',
      en: "I'm a pair of white running shoes. I only ran two marathons. There's a small scuff on the left. It's from crossing my first finish line.",
    },
    ownerNote: {
      zh: '飞飞陪我跑过两次全马，现在脚受伤了不能跑了，但鞋子还是好的。',
      en: "Fei-Fei ran two full marathons with me. A foot injury stops me now, but the shoes are still in great shape.",
    },
    category: 'fashion',
    condition: 'gentleUse',
    district: { zh: '朝阳区', en: 'Chaoyang' },
    city: { zh: '北京', en: 'Beijing' },
    distance: 1500,
    price: 29,
    timestamp: Date.now() - 6 * 24 * 60 * 60 * 1000,
    status: 'waiting',
    views: 178,
    owner: {
      id: 7,
      nickname: '刘跑者',
      avatarUrl: 'https://www.keaitupian.cn/cjpic/frombd/2/253/3296707720/1955418873.jpg',
      bio: {
        zh: '跑步爱好者，现在脚受伤了暂时跑不了。希望飞飞继续陪伴下一个跑者。',
        en: 'Running enthusiast, currently injured and can\'t run. Hoping Fei-Fei finds a new runner to accompany.',
      },
    },
  },
  {
    id: 8,
    photo: 'https://images.unsplash.com/photo-1573104049264-5324ea0027d5?q=80&w=3271&auto=format&fit=crop',
    name: { zh: '小桌', en: 'Little Desk' },
    story: {
      zh: '我是一张实木书桌，陪主人读过100多本书。桌面有几道笔痕，每一道都是一次灵感的痕迹。',
      en: "I'm a solid wood desk. I've supported someone through over 100 books. The pen marks on my surface? Each one is a spark of inspiration.",
    },
    ownerNote: {
      zh: '搬家实在带不走，但它陪我熬过了多少个夜晚，舍不得扔。',
      en: "Can't take it when moving, but this desk saw me through countless late nights. Can't just throw it away.",
    },
    category: 'home',
    condition: 'hasCharacter',
    district: { zh: '海淀区', en: 'Haidian' },
    city: { zh: '北京', en: 'Beijing' },
    distance: 5500,
    price: 85,
    timestamp: Date.now() - 10 * 24 * 60 * 60 * 1000,
    status: 'waiting',
    views: 421,
    owner: {
      id: 8,
      nickname: '周书生',
      avatarUrl: 'https://www.keaitupian.cn/cjpic/frombd/0/253/572092993/2464038626.jpg',
      bio: {
        zh: '读书人，搬家带不走的只有回忆和这张桌子。希望找到爱书的人。',
        en: 'A reader with more memories than luggage. This desk and I have seen a lot of books together.',
      },
    },
  },
  {
    id: 9,
    photo: 'https://images.unsplash.com/photo-1572635196237-14b3f281503f?w=400&h=400&fit=crop',
    name: { zh: '小墨', en: 'Little Ink' },
    story: {
      zh: '我是一副墨镜，跟着主人去过海边和雪山。镜片有一道小划痕，但看世界还是彩色的。',
      en: "I'm a pair of sunglasses. I've been to beaches and snowy mountains with my owner. One small scratch on the lens, but the world still looks colorful.",
    },
    ownerNote: {
      zh: '买了一副新的，这副旧的就交给你啦。',
      en: "Bought a new pair. This one's ready for its next adventure.",
    },
    category: 'fashion',
    condition: 'gentleUse',
    district: { zh: '朝阳区', en: 'Chaoyang' },
    city: { zh: '北京', en: 'Beijing' },
    distance: 950,
    price: 23,
    timestamp: Date.now() - 8 * 24 * 60 * 60 * 1000,
    status: 'waiting',
    views: 134,
    owner: {
      id: 9,
      nickname: '赵旅行者',
      avatarUrl: 'https://www.keaitupian.cn/cjpic/frombd/0/253/2394782721/3427402308.jpg',
      bio: {
        zh: '旅行达人，去过很多地方。这副墨镜陪我走过很多旅途，现在想让它继续旅行。',
        en: 'Seasoned traveler who has been many places. These sunglasses traveled far with me. Time for them to continue the journey.',
      },
    },
  },
  {
    id: 10,
    photo: 'https://images.unsplash.com/photo-1524592094714-0f0654e20314?q=80&w=2798&auto=format&fit=crop',
    name: { zh: '小表', en: 'Little Watch' },
    story: {
      zh: '我是一块机械表，每天上发针才能走动。主人嫌麻烦换智能手表了，但我觉得每天上发针是一种仪式感。',
      en: "I'm a mechanical watch. You need to wind me daily to keep ticking. My owner switched to a smart watch, but I think winding me every day is a kind of ritual.",
    },
    ownerNote: {
      zh: '爷爷送的表，现在换成了smartwatch。希望有人珍惜它。',
      en: 'A watch from my grandfather. Switched to a smartwatch now. Hope someone cherishes it.',
    },
    category: 'fashion',
    condition: 'hasCharacter',
    district: { zh: '西城区', en: 'Xicheng' },
    city: { zh: '北京', en: 'Beijing' },
    distance: 7800,
    price: 128,
    timestamp: Date.now() - 15 * 24 * 60 * 60 * 1000,
    status: 'waiting',
    views: 256,
    owner: {
      id: 10,
      nickname: '陈怀旧',
      avatarUrl: 'https://www.keaitupian.cn/cjpic/frombd/1/253/3238347855/4149147509.jpg',
      bio: {
        zh: '怀旧的人，爷爷留下的机械表。现在有了智能手表，但机械表的手感无法替代。',
        en: 'A sentimental person. This mechanical watch was my grandfather\'s. Smartwatches are practical, but nothing beats the feel of a mechanical watch.',
      },
    },
  },
  {
    id: 11,
    photo: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=400&h=400&fit=crop',
    name: { zh: '小音', en: 'Little Sound' },
    story: {
      zh: '我是一副无线耳机，音质很好，只是主人丢了左耳那只。右耳的我还在等一个完整的机会。',
      en: "I'm a wireless earphone. Great sound quality, but my owner lost the left one. The right one (that's me!) is still waiting for a chance to be complete again.",
    },
    ownerNote: {
      zh: '丢了左耳的耳机，右耳的还在。虽然不完整但音质真的很好。',
      en: 'Lost the left earbud. The right one remains. And honestly, the sound quality is still amazing.',
    },
    category: 'digital',
    condition: 'gentleUse',
    district: { zh: '海淀区', en: 'Haidian' },
    city: { zh: '北京', en: 'Beijing' },
    distance: 2300,
    price: 45,
    timestamp: Date.now() - 12 * 24 * 60 * 60 * 1000,
    status: 'waiting',
    views: 312,
    owner: {
      id: 11,
      nickname: '马丢三',
      avatarUrl: 'https://www.keaitupian.cn/cjpic/frombd/0/253/1440620448/106605265.jpg',
      bio: {
        zh: '总是丢三落四的，耳机左耳丢了不下三次了。希望小音找到一个细心的新主人。',
        en: 'Always losing things. My left earbuds have gone missing more times than I can count. Hoping Little Sound finds a more careful owner.',
      },
    },
  },
  {
    id: 12,
    photo: 'https://images.unsplash.com/photo-1652501595862-1d06fe543544?q=80&w=3270&auto=format&fit=crop',
    name: { zh: '小熊', en: 'Little Bear' },
    story: {
      zh: '我是一只毛绒小熊，陪一个小女孩度过了整个童年。现在我该去陪伴另一个需要温暖的人了。',
      en: "I'm a teddy bear who stayed with a little girl through her entire childhood. Now it's time to bring warmth to someone else.",
    },
    ownerNote: {
      zh: '女儿长大了不再抱小熊了，但它很干净很软，希望有新主人。',
      en: "My daughter outgrew her teddy, but it's clean and soft. Hope it finds a new friend.",
    },
    category: 'toys',
    condition: 'likeNew',
    district: { zh: '朝阳区', en: 'Chaoyang' },
    city: { zh: '北京', en: 'Beijing' },
    distance: 3100,
    price: 0,
    timestamp: Date.now() - 9 * 24 * 60 * 60 * 1000,
    status: 'waiting',
    views: 445,
    owner: {
      id: 12,
      nickname: '小米',
      avatarUrl: 'https://www.keaitupian.cn/cjpic/frombd/2/253/1384495307/2841456444.jpg',
      bio: {
        zh: '家里小朋友长大了，小熊还很新，希望找到会珍惜它的新主人。',
        en: 'Our little girl has grown up. The bear is still in great shape and deserves a new friend who will cherish it.',
      },
    },
  },
  {
    id: 13,
    photo: 'https://images.unsplash.com/photo-1656274866692-c78b0b013d27?q=80&w=3270&auto=format&fit=crop',
    name: { zh: '小画', en: 'Little Paint' },
    story: {
      zh: '我是一套水彩颜料，主人只用了三分之一。色彩还很鲜艳，等待能画出美丽风景的人。',
      en: "I'm a watercolor set, only a third used. Colors are still vibrant, waiting for someone to paint beautiful landscapes.",
    },
    ownerNote: {
      zh: '买了但没时间画，颜料都是好的。',
      en: "Bought it but never had time to paint. All the paints are still good.",
    },
    category: 'others',
    condition: 'likeNew',
    district: { zh: '海淀区', en: 'Haidian' },
    city: { zh: '北京', en: 'Beijing' },
    distance: 4700,
    price: 32,
    timestamp: Date.now() - 14 * 24 * 60 * 60 * 1000,
    status: 'waiting',
    views: 89,
    owner: {
      id: 13,
      nickname: '林艺术家',
      avatarUrl: 'https://www.keaitupian.cn/cjpic/frombd/2/253/80195369/1696099480.jpg',
      bio: {
        zh: '艺术从业者，买了颜料却没时间画。希望它们找到下一个创作者。',
        en: 'Artist who bought these paints but never found time to use them. Hoping they find a creator who will put them to good use.',
      },
    },
  },
  {
    id: 14,
    photo: 'https://images.unsplash.com/photo-1675523796635-d6e4d8a127b1?q=80&w=1267&auto=format&fit=crop',
    name: { zh: '小喇叭', en: 'Little Speaker' },
    story: {
      zh: '我是一个便携音箱，音质很好，低音特别棒。主人换了新的，但我觉得我还很能打。',
      en: "I'm a portable speaker with great sound, especially deep bass. My owner got an upgrade, but I still think I've got plenty to offer.",
    },
    ownerNote: {
      zh: '音质很好的小音箱，换了新的所以这个闲置了。',
      en: "Great sound quality speaker. Got a new one so this one's idle.",
    },
    category: 'digital',
    condition: 'gentleUse',
    district: { zh: '朝阳区', en: 'Chaoyang' },
    city: { zh: '北京', en: 'Beijing' },
    distance: 1800,
    price: 56,
    timestamp: Date.now() - 11 * 24 * 60 * 60 * 1000,
    status: 'waiting',
    views: 223,
    owner: {
      id: 14,
      nickname: '赵音乐',
      avatarUrl: 'https://www.keaitupian.cn/cjpic/frombd/0/253/1039890271/3926485754.jpg',
      bio: {
        zh: '音乐爱好者，更换了新音箱后老音箱闲置了。低音效果特别好，希望找到懂它的人。',
        en: 'Music lover who upgraded to a newer speaker. The bass on this one is incredible. Hoping it finds someone who can appreciate it.',
      },
    },
  },
  {
    id: 15,
    photo: 'https://images.unsplash.com/photo-1712933765020-a1f2384c65d2?q=80&w=3274&auto=format&fit=crop',
    name: { zh: '小壶', en: 'Little Pot' },
    story: {
      zh: '我是一个紫砂壶，泡过的茶越多颜色越好看。主人搬家带不走了，希望有人继续养我。',
      en: "I'm a purple clay teapot. The more tea I brew, the more beautiful I become. My owner can't take me when moving. Hope someone keeps nurturing me.",
    },
    ownerNote: {
      zh: '养了2年的紫砂壶，搬家实在不方便，给它找个新家。',
      en: 'A purple clay teapot I cared for 2 years. Moving is hard. Finding it a new home.',
    },
    category: 'home',
    condition: 'hasCharacter',
    district: { zh: '东城区', en: 'Dongcheng' },
    city: { zh: '北京', en: 'Beijing' },
    distance: 6800,
    price: 75,
    timestamp: Date.now() - 13 * 24 * 60 * 60 * 1000,
    status: 'waiting',
    views: 187,
    owner: {
      id: 15,
      nickname: '郑茶人',
      avatarUrl: 'https://www.keaitupian.cn/cjpic/frombd/2/253/516032643/785442728.jpg',
      bio: {
        zh: '茶文化爱好者，养了两年的紫砂壶。搬家带不走，希望找到爱茶的新主人。',
        en: 'Tea culture enthusiast who nurtured this purple clay teapot for 2 years. Moving and can\'t take it. Hoping it finds a tea-loving new owner.',
      },
    },
  },
  {
    id: 16,
    photo: 'https://images.unsplash.com/photo-1618384887929-16ec33fab9ef?w=800&h=800&fit=crop',
    name: { zh: '小键盘', en: 'Little Keyboard' },
    story: {
      zh: '我是一个机械键盘，每个键都敲过上千次。青轴的声音像音乐，但主人嫌吵换静音的了。',
      en: "I'm a mechanical keyboard. Every key has been pressed thousands of times. My blue switches sound like music, but my owner switched to silent ones.",
    },
    ownerNote: {
      zh: '同事说太吵了换静音键盘了，这个还是好用的。',
      en: "Coworkers said it was too loud so I got a silent one. This one works perfectly fine.",
    },
    category: 'digital',
    condition: 'hasCharacter',
    district: { zh: '海淀区', en: 'Haidian' },
    city: { zh: '北京', en: 'Beijing' },
    distance: 3800,
    price: 98,
    timestamp: Date.now() - 16 * 24 * 60 * 60 * 1000,
    status: 'waiting',
    views: 367,
    owner: {
      id: 16,
      nickname: '赵码农',
      avatarUrl: 'https://www.keaitupian.cn/cjpic/frombd/2/253/2299501635/3877934376.jpg',
      bio: {
        zh: '程序员，小键盘是我的老伙计。现在换了静音轴，想让它找个懂它的人。',
        en: 'A programmer. This keyboard and I logged countless hours together. Now that I have a silent one, it deserves someone who appreciates its sound.',
      },
    },
  },
  {
    id: 17,
    photo: 'https://images.unsplash.com/photo-1613483762885-465411d2eef4?q=80&w=1374&auto=format&fit=crop',
    name: { zh: '小伞', en: 'Little Umbrella' },
    story: {
      zh: '我是一把长柄雨伞，伞骨很结实。陪主人度过很多个雨天，但她说折叠伞更方便。',
      en: "I'm a long-handle umbrella with sturdy ribs. I stayed with my owner through many rainy days, but she says folding umbrellas are more convenient.",
    },
    ownerNote: {
      zh: '质量很好的雨伞，只是换了折叠的。',
      en: "A really well-made umbrella, just switched to a folding one.",
    },
    category: 'others',
    condition: 'likeNew',
    district: { zh: '朝阳区', en: 'Chaoyang' },
    city: { zh: '北京', en: 'Beijing' },
    distance: 500,
    price: 0,
    timestamp: Date.now() - 17 * 24 * 60 * 60 * 1000,
    status: 'waiting',
    views: 156,
    owner: {
      id: 17,
      nickname: '小雨',
      avatarUrl: 'https://www.keaitupian.cn/cjpic/frombd/2/253/2180828201/1483470241.jpg',
      bio: {
        zh: '总是忘带伞的人，现在只用折叠伞了。这把长柄伞质量很好，扔了可惜。',
        en: 'Always forgetting umbrellas. Now I only use folding ones. This long-handle umbrella is still in great shape.',
      },
    },
  },
  {
    id: 18,
    photo: 'https://images.unsplash.com/photo-1641412722397-3be359096577?q=80&w=1635&auto=format&fit=crop',
    name: { zh: '小盆栽', en: 'Little Bonsai' },
    story: {
      zh: '我是一颗小树盆栽，被修剪了3年，现在终于有点像一棵真正的盆景了。',
      en: "I'm a small tree bonsai, pruned for 3 years, and I'm finally starting to look like a real miniature landscape.",
    },
    ownerNote: {
      zh: '修剪了3年的盆栽，出差没人照顾，需要有心人。',
      en: '3 years of pruning. Business trips leave it untended. Needs someone attentive.',
    },
    category: 'home',
    condition: 'likeNew',
    district: { zh: '西城区', en: 'Xicheng' },
    city: { zh: '北京', en: 'Beijing' },
    distance: 8900,
    price: 42,
    timestamp: Date.now() - 20 * 24 * 60 * 60 * 1000,
    status: 'waiting',
    views: 234,
    owner: {
      id: 18,
      nickname: '孙园丁',
      avatarUrl: 'https://www.keaitupian.cn/cjpic/frombd/1/253/1900896837/2315891817.jpg',
      bio: {
        zh: '园艺爱好者，修剪了3年的盆景。现在出差太频繁，顾不上了。',
        en: 'Gardening enthusiast who pruned this bonsai for 3 years. Business trips make it hard to care for it now.',
      },
    },
  },
  {
    id: 19,
    photo: 'https://picsum.photos/seed/xiaoluhui/400/400',
    name: { zh: '小芦荟', en: 'Little Aloe' },
    story: {
      zh: '我是一盆芦荟，很坚强，不怎么需要照顾。主人要出国了，希望有人不要把我忘了就好。',
      en: "I'm an aloe plant. Very tough, don't need much care. My owner is going abroad, just hoping someone won't forget about me.",
    },
    ownerNote: {
      zh: '出国了带不走，芦荟很好养活，需要的联系我。',
      en: "Going abroad, can't take it. Aloe is easy to care for. Reach out.",
    },
    category: 'home',
    condition: 'likeNew',
    district: { zh: '朝阳区', en: 'Chaoyang' },
    city: { zh: '北京', en: 'Beijing' },
    distance: 2800,
    price: 0,
    timestamp: Date.now() - 22 * 24 * 60 * 60 * 1000,
    status: 'found',
    views: 189,
    owner: {
      id: 19,
      nickname: '林出国',
      avatarUrl: 'https://www.keaitupian.cn/cjpic/frombd/2/253/1111172100/982454911.jpg',
      bio: {
        zh: '即将出国，芦荟带不走。好养活的小植物，希望有人接手。',
        en: 'About to go abroad. This aloe is easy to care for and tough as nails. Hoping someone takes it.',
      },
    },
  },
  {
    id: 20,
    photo: 'https://images.unsplash.com/photo-1543076447-215ad9ba6923?q=80&w=2748&auto=format&fit=crop',
    name: { zh: '小外套', en: 'Little Coat' },
    story: {
      zh: '我是一件牛仔外套，穿出去回头率100%。主人减肥成功了，尺码小了穿不上了。',
      en: "I'm a denim jacket. When you wear me, people look. 100%回头率. My owner lost weight and I'm too small now.",
    },
    ownerNote: {
      zh: '很好看的外套，就是瘦了穿不上，希望找到合适的人。',
      en: "Really nice jacket, just outgrew it after losing weight. Hope it finds the right fit.",
    },
    category: 'fashion',
    condition: 'likeNew',
    district: { zh: '海淀区', en: 'Haidian' },
    city: { zh: '北京', en: 'Beijing' },
    distance: 5200,
    price: 55,
    timestamp: Date.now() - 25 * 24 * 60 * 60 * 1000,
    status: 'waiting',
    views: 378,
    owner: {
      id: 20,
      nickname: '王减肥',
      avatarUrl: 'https://www.keaitupian.cn/cjpic/frombd/2/253/1509649422/4177602926.jpg',
      bio: {
        zh: '健身成功瘦了很多，以前的衣服都穿不上了。外套很新，希望找到合适的新主人。',
        en: 'Lost a lot of weight through fitness. My old clothes no longer fit. This jacket is still new. Hoping it finds someone with the right fit.',
      },
    },
  },
];